/**
 * This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.wavemaker.sampleapps.wavekart.invoicereportservice.controller;

import com.wavemaker.sampleapps.wavekart.invoicereportservice.InvoiceReportService;
import com.wavemaker.runtime.file.model.DownloadResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/invoiceReport")
public class InvoiceReportController {

    @Autowired
    private InvoiceReportService invoiceReportService;

    @RequestMapping(value = "/generatePdfReport", produces = "application/octet-stream", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public DownloadResponse generatePdfReport(@RequestParam(value = "orderId", required = false) int orderId) {
        return invoiceReportService.generatePdfReport(orderId);
    }
}
