/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/
package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.wavemaker.sampleapps.wavekart.eshopping.models.query.*;

@Service
public class EshoppingQueryExecutorServiceImpl_V1 implements EshoppingQueryExecutorService_V1 {

    private static final Logger LOGGER = LoggerFactory.getLogger(EshoppingQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("eshoppingWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "eshoppingTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeTotalItemsPrice_CartProd(Pageable pageable, Integer cartId) {
        Map params = new HashMap(1);

        params.put("cartId", cartId);

        return queryExecutor.executeNamedQuery("TotalItemsPrice_CartProd", params, Object.class, pageable);
    }

    @Transactional(value = "eshoppingTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeTotalItemsPrice_Orders(Pageable pageable, Integer oid) {
        Map params = new HashMap(1);

        params.put("Oid", oid);

        return queryExecutor.executeNamedQuery("TotalItemsPrice_Orders", params, Object.class, pageable);
    }

    @Transactional(value = "eshoppingTransactionManager")
    @Override
    public int executeDeleteCartItems_LoggedUser(Integer loggedUserCartId) {
        Map params = new HashMap(1);

        params.put("LoggedUserCartId", loggedUserCartId);

        return queryExecutor.executeNamedQueryForUpdate("DeleteCartItems_LoggedUser", params);
    }

    @Transactional(value = "eshoppingTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeGet_CartIdByUserid(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("Get_CartIdByUserid", params, Object.class, pageable);
    }

    @Transactional(value = "eshoppingTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeMyCart_Items_Count(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("MyCart_Items_Count", params, Object.class, pageable);
    }

    @Transactional(value = "eshoppingTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeGet_CartItems_id(Pageable pageable, Integer cid) {
        Map params = new HashMap(1);

        params.put("Cid", cid);

        return queryExecutor.executeNamedQuery("Get_CartItems_id", params, Object.class, pageable);
    }

}