/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/
package com.wavemaker.sampleapps.wavekart.eshopping.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetCartIdByUseridResponse implements Serializable {


    @JsonProperty("CART_ID")
    @ColumnAlias("CART_ID")
    private Integer cartId;

    public Integer getCartId() {
        return this.cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetCartIdByUseridResponse)) return false;
        final GetCartIdByUseridResponse getCartIdByUseridResponse = (GetCartIdByUseridResponse) o;
        return Objects.equals(getCartId(), getCartIdByUseridResponse.getCartId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCartId());
    }
}