/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/
package com.wavemaker.sampleapps.wavekart.eshopping.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QvGetInventoryDetailsResponse implements Serializable {


    @ColumnAlias("QUANTITY")
    private BigInteger quantity;

    public BigInteger getQuantity() {
        return this.quantity;
    }

    public void setQuantity(BigInteger quantity) {
        this.quantity = quantity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QvGetInventoryDetailsResponse)) return false;
        final QvGetInventoryDetailsResponse qvGetInventoryDetailsResponse = (QvGetInventoryDetailsResponse) o;
        return Objects.equals(getQuantity(), qvGetInventoryDetailsResponse.getQuantity());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getQuantity());
    }
}