/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/
package com.wavemaker.sampleapps.wavekart.eshopping.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class QvUpdateQuantityFromPiRequest implements Serializable {


    @JsonProperty("qty")
    @NotNull
    private Integer qty;

    @JsonProperty("productId")
    @NotNull
    private Integer productId;

    public Integer getQty() {
        return this.qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QvUpdateQuantityFromPiRequest)) return false;
        final QvUpdateQuantityFromPiRequest qvUpdateQuantityFromPiRequest = (QvUpdateQuantityFromPiRequest) o;
        return Objects.equals(getQty(), qvUpdateQuantityFromPiRequest.getQty()) &&
                Objects.equals(getProductId(), qvUpdateQuantityFromPiRequest.getProductId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getQty(),
                getProductId());
    }
}