/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/
package com.wavemaker.sampleapps.wavekart.eshopping;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class OrderLineItemsId implements Serializable {

    private Integer orderId;
    private Integer productId;

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof OrderLineItems)) return false;
        final OrderLineItems orderLineItems = (OrderLineItems) o;
        return Objects.equals(getOrderId(), orderLineItems.getOrderId()) &&
                Objects.equals(getProductId(), orderLineItems.getProductId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrderId(),
                getProductId());
    }
}